version: '3.8'
services:
  api:
    profiles:
      - all
    build: .
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - dbpostgresql
      - minio
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_URL
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SITE_REGION
      - MINIO_BUCKET
      - CLIENT_ID
      - CLIENT_SECRET
  dbpostgresql:
    profiles:
      - dev
      - all
      - db
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_URL
  minio:
    profiles:
      - dev
      - all
      - minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SITE_REGION
  #createbuckets:
  #  image: minio/mc
  #  profiles:
  #    - dev
  #    - all
  #    - minio
  #  depends_on:
  #    - minio
  #  entrypoint: >
  #    /bin/sh -c "
  #    /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --api S3v4;
  #    /usr/bin/mc mb myminio/images;
  #    /usr/bin/mc ls myminio;
  #    /usr/bin/mc policy set public myminio/images;
  #    exit 0;
  #    "
volumes:
  minio_data:
    driver: local

