version: '3.8'
services:
  api:
    profiles:
      - dev
    build: .
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - dbpostgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_URL=jdbc:postgresql://dbpostgresql:5432/crmdb
  dbpostgresql:
    profiles:
      - db
      - dev
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_URL=jdbc:postgresql://dbpostgresql:5432/crmdb