spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${env.CLIENT_ID}
            clientSecret: ${env.CLIENT_SECRET}
minio:
  url: http://localhost:9000
  bucket: ${env.MINIO_BUCKET}
  access-key: ${env.MINIO_ROOT_USER}
  secret-key: ${env.MINIO_ROOT_PASSWORD}
  region: ${env.MINIO_SITE_REGION}
security:
  enable: false
email:
  baseUrl: https://api.mailgun.net/v3/${env.DOMAIN_NAME}/messages
  apiKey: ${env.API_KEY}