
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${env.CLIENT_ID}
            clientSecret: ${env.CLIENT_SECRET}
admin:
  paths: /v1/users,/v1/util,/v1/storage
auth:
  paths: /v1
minio:
  url: ${MINIO_URL}
  bucket: ${MINIO_BUCKET}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  region: ${MINIO_SITE_REGION}
security:
  enable: true
email:
  baseUrl: https://api.mailgun.net/v3/${DOMAIN_NAME}/messages
  from: noreply@tam.com
  apiKey: ${API_KEY}
csv:
  separator: ','
  quote: '"'
  header: photo, name, surname, email
